"""nuevo modelo Category para productos y ajustes varios

Revision ID: bcb4184a427c
Revises: c8c6f928dee6
Create Date: 2026-05-23 10:09:18.856752

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bcb4184a427c'
down_revision: str | Sequence[str] | None = 'c8c6f928dee6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS product;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('product_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='product'
    )
    op.create_table('json_web_token_blacklist',
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index(
        op.f('ix_auth_json_web_token_blacklist_token'),
        'json_web_token_blacklist',
        ['token'],
        unique=True,
        schema='auth'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_auth_json_web_token_blacklist_token'),
        table_name='json_web_token_blacklist',
        schema='auth'
    )
    op.drop_table('json_web_token_blacklist', schema='auth')
    op.drop_table('categories', schema='product')
    # ### end Alembic commands ###
