"""reinicio de las migraciones

Revision ID: cbd59498ef6b
Revises: 
Create Date: 2026-05-26 19:29:34.390295

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cbd59498ef6b'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    
    op.execute("CREATE SCHEMA IF NOT EXISTS auth;")
    op.execute("CREATE SCHEMA IF NOT EXISTS customer;")
    op.execute("CREATE SCHEMA IF NOT EXISTS product;")
    op.execute("CREATE SCHEMA IF NOT EXISTS admin;")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_groups_name'), 'groups', ['name'], unique=True, schema='auth')
    op.create_table('permissions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_permissions_name'), 'permissions', ['name'], unique=True, schema='auth')
    op.create_table('users',
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='auth'
    )
    op.create_table('categories',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('product_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='product'
    )
    op.create_table('products',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('categories', sa.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('description_short', sa.String(length=100), nullable=False),
    sa.Column('description_long', sa.String(length=1000), nullable=False),
    sa.Column('images', sa.ARRAY(sa.String(length=2048)), nullable=False),
    sa.Column('price_neto', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('price_sale', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('stock_total', sa.Integer(), nullable=False),
    sa.Column('stock_hand', sa.Integer(), nullable=False),
    sa.Column('stock_sale', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='product'
    )
    op.create_table('admins',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('first_names', sa.String(length=40), nullable=True),
    sa.Column('last_names', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='admin'
    )
    op.create_table('json_web_token_blacklist',
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_json_web_token_blacklist_token'), 'json_web_token_blacklist', ['token'], unique=True, schema='auth')
    op.create_table('permission_groups',
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth.groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['auth.permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_table('user_groups',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth.groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_table('customers',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('first_names', sa.String(length=40), nullable=True),
    sa.Column('last_names', sa.String(length=40), nullable=True),
    sa.Column('document_type', sa.String(length=9), nullable=True),
    sa.Column('document_number', sa.String(length=13), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_number'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('user_id'),
    schema='customer'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers', schema='customer')
    op.drop_table('user_groups', schema='auth')
    op.drop_table('permission_groups', schema='auth')
    op.drop_index(op.f('ix_auth_json_web_token_blacklist_token'), table_name='json_web_token_blacklist', schema='auth')
    op.drop_table('json_web_token_blacklist', schema='auth')
    op.drop_table('admins', schema='admin')
    op.drop_table('products', schema='product')
    op.drop_table('categories', schema='product')
    op.drop_table('users', schema='auth')
    op.drop_index(op.f('ix_auth_permissions_name'), table_name='permissions', schema='auth')
    op.drop_table('permissions', schema='auth')
    op.drop_index(op.f('ix_auth_groups_name'), table_name='groups', schema='auth')
    op.drop_table('groups', schema='auth')
    # ### end Alembic commands ###
