"""cambio del nombre de la llave foranea exclusive_client_id

Revision ID: e36327183d95
Revises: 6f156b46a2f9
Create Date: 2026-10-01 10:16:28.495313

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e36327183d95"
down_revision: str | Sequence[str] | None = "6f156b46a2f9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("wholesaler_id", sa.Uuid(), nullable=True), schema="inventory"
    )
    op.drop_constraint(
        op.f("fk_products_exclusive_client_id_customer_wholesale"),
        "products",
        schema="inventory",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_products_wholesaler_id_customer_wholesale"),
        "products",
        "customer_wholesale",
        ["wholesaler_id"],
        ["id"],
        source_schema="inventory",
        referent_schema="users",
        ondelete="CASCADE",
    )
    op.drop_column("products", "exclusive_client_id", schema="inventory")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("exclusive_client_id", sa.UUID(), autoincrement=False, nullable=True),
        schema="inventory",
    )
    op.drop_constraint(
        op.f("fk_products_wholesaler_id_customer_wholesale"),
        "products",
        schema="inventory",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_products_exclusive_client_id_customer_wholesale"),
        "products",
        "customer_wholesale",
        ["exclusive_client_id"],
        ["id"],
        source_schema="inventory",
        referent_schema="users",
        ondelete="CASCADE",
    )
    op.drop_column("products", "wholesaler_id", schema="inventory")
    # ### end Alembic commands ###
