"""Ajuste de implementación para el modelo User

Revision ID: a5f20dc1b98a
Revises: c8199cae5744
Create Date: 2026-04-11 12:05:57.357398

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5f20dc1b98a'
down_revision: str | Sequence[str] | None = 'c8199cae5744'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'document_type',
               existing_type=postgresql.ENUM(name='document_type_enum'),
               type_=sa.String(length=9),
               existing_nullable=True,
               schema='customer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'document_type',
               existing_type=sa.String(length=9),
               type_=postgresql.ENUM(name='document_type_enum'),
               existing_nullable=True,
               schema='customer')
    # ### end Alembic commands ###
