"""esquema inicial con convencion de nombres

Revision ID: c9bba5404f8a
Revises: 
Create Date: 2026-09-29 09:59:27.808344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9bba5404f8a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups')),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_groups_name'), 'groups', ['name'], unique=True, schema='auth')
    op.create_table('permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_permissions_name'), 'permissions', ['name'], unique=True, schema='auth')
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    schema='auth'
    )
    op.create_table('canton_ecuador',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_canton_ecuador')),
    sa.UniqueConstraint('name', name=op.f('uq_canton_ecuador_name')),
    schema='countries'
    )
    op.create_table('city_ecuador',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_city_ecuador')),
    sa.UniqueConstraint('name', name=op.f('uq_city_ecuador_name')),
    schema='countries'
    )
    op.create_table('country',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('administrative_structure', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_country')),
    sa.UniqueConstraint('name', name=op.f('uq_country_name')),
    schema='countries'
    )
    op.create_table('province_ecuador',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_province_ecuador')),
    sa.UniqueConstraint('name', name=op.f('uq_province_ecuador_name')),
    schema='countries'
    )
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('product_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name')),
    schema='product'
    )
    op.create_table('wholesale',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name_or_company_name', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('ruc', sa.String(length=13), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=False),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extra_contacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wholesale')),
    sa.UniqueConstraint('email', name=op.f('uq_wholesale_email')),
    sa.UniqueConstraint('name_or_company_name', name=op.f('uq_wholesale_name_or_company_name')),
    sa.UniqueConstraint('phone', name=op.f('uq_wholesale_phone')),
    sa.UniqueConstraint('ruc', name=op.f('uq_wholesale_ruc')),
    schema='users'
    )
    op.create_table('permission_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth.groups.id'], name=op.f('fk_permission_groups_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['auth.permissions.id'], name=op.f('fk_permission_groups_permission_id_permissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permission_groups')),
    schema='auth'
    )
    op.create_table('user_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['auth.groups.id'], name=op.f('fk_user_groups_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_user_groups_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_groups')),
    schema='auth'
    )
    op.create_table('organization_ecuador',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('country_id', sa.Uuid(), nullable=False),
    sa.Column('province_id', sa.Uuid(), nullable=False),
    sa.Column('canton_id', sa.Uuid(), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['canton_id'], ['countries.canton_ecuador.id'], name=op.f('fk_organization_ecuador_canton_id_canton_ecuador'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['city_id'], ['countries.city_ecuador.id'], name=op.f('fk_organization_ecuador_city_id_city_ecuador'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country.id'], name=op.f('fk_organization_ecuador_country_id_country'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['province_id'], ['countries.province_ecuador.id'], name=op.f('fk_organization_ecuador_province_id_province_ecuador'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_ecuador')),
    schema='countries'
    )
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exclusive_client_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('categories', sa.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('description_short', sa.String(length=100), nullable=False),
    sa.Column('description_long', sa.String(length=1000), nullable=False),
    sa.Column('images', sa.ARRAY(sa.String(length=2048)), nullable=False),
    sa.Column('price_neto', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('price_sale', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('profit_margin', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('iva', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('stock_total', sa.Integer(), nullable=False),
    sa.Column('stock_hand', sa.Integer(), nullable=False),
    sa.Column('stock_sale', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exclusive_client_id'], ['users.wholesale.id'], name=op.f('fk_products_exclusive_client_id_wholesale'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('name', name=op.f('uq_products_name')),
    schema='product'
    )
    op.create_index(op.f('ix_product_products_status'), 'products', ['status'], unique=False, schema='product')
    op.create_table('admins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('first_names', sa.String(length=40), nullable=False),
    sa.Column('last_names', sa.String(length=40), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_admins_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admins')),
    sa.UniqueConstraint('user_id', name=op.f('uq_admins_user_id')),
    schema='users'
    )
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('first_names', sa.String(length=40), nullable=False),
    sa.Column('last_names', sa.String(length=40), nullable=False),
    sa.Column('document_type', sa.String(length=9), nullable=True),
    sa.Column('document_number', sa.String(length=13), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_customers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('document_number', name=op.f('uq_customers_document_number')),
    sa.UniqueConstraint('phone', name=op.f('uq_customers_phone')),
    sa.UniqueConstraint('user_id', name=op.f('uq_customers_user_id')),
    schema='users'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers', schema='users')
    op.drop_table('admins', schema='users')
    op.drop_index(op.f('ix_product_products_status'), table_name='products', schema='product')
    op.drop_table('products', schema='product')
    op.drop_table('organization_ecuador', schema='countries')
    op.drop_table('user_groups', schema='auth')
    op.drop_table('permission_groups', schema='auth')
    op.drop_table('wholesale', schema='users')
    op.drop_table('categories', schema='product')
    op.drop_table('province_ecuador', schema='countries')
    op.drop_table('country', schema='countries')
    op.drop_table('city_ecuador', schema='countries')
    op.drop_table('canton_ecuador', schema='countries')
    op.drop_table('users', schema='auth')
    op.drop_index(op.f('ix_auth_permissions_name'), table_name='permissions', schema='auth')
    op.drop_table('permissions', schema='auth')
    op.drop_index(op.f('ix_auth_groups_name'), table_name='groups', schema='auth')
    op.drop_table('groups', schema='auth')
    # ### end Alembic commands ###
