"""nuevo modelo admin

Revision ID: 0b3eb6f73b20
Revises: 24288c210103
Create Date: 2026-05-01 13:35:53.815922

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0b3eb6f73b20'
down_revision: str | Sequence[str] | None = '24288c210103'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    
    op.execute("CREATE SCHEMA IF NOT EXISTS admin;")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('first_names', sa.String(length=40), nullable=True),
    sa.Column('last_names', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='admin'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins', schema='admin')
    # ### end Alembic commands ###
