"""se elimino modelo y repositorio asociado a los JWT

Revision ID: 165aaee1d392
Revises: 0682cbc0a5c7
Create Date: 2026-07-01 15:12:51.609934

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '165aaee1d392'
down_revision: str | Sequence[str] | None = '0682cbc0a5c7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_json_web_token_blacklist_jti'), table_name='json_web_token_blacklist', schema='auth')
    op.drop_index(op.f('ix_auth_json_web_token_blacklist_token_type'), table_name='json_web_token_blacklist', schema='auth')
    op.drop_table('json_web_token_blacklist', schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('json_web_token_blacklist',
    sa.Column('token', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('jti', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('token_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('date_joined', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('json_web_token_blacklist_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('json_web_token_blacklist_pkey')),
    sa.UniqueConstraint('token', name=op.f('json_web_token_blacklist_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_json_web_token_blacklist_token_type'), 'json_web_token_blacklist', ['token_type'], unique=True, schema='auth')
    op.create_index(op.f('ix_auth_json_web_token_blacklist_jti'), 'json_web_token_blacklist', ['jti'], unique=True, schema='auth')
    # ### end Alembic commands ###
