"""ajustes en todos los modelos

Revision ID: dbc78487bfd6
Revises: cbd59498ef6b
Create Date: 2026-06-16 19:43:04.198730

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbc78487bfd6'
down_revision: str | Sequence[str] | None = 'cbd59498ef6b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'user_id',
               existing_type=sa.UUID(),
               nullable=True,
               schema='admin')
    op.alter_column('admins', 'date_joined',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               schema='admin')
    op.alter_column('groups', 'date_joined',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               schema='auth')
    op.alter_column('json_web_token_blacklist', 'token',
               existing_type=sa.VARCHAR(length=512),
               nullable=True,
               schema='auth')
    op.alter_column('json_web_token_blacklist', 'user_id',
               existing_type=sa.UUID(),
               nullable=True,
               schema='auth')
    op.alter_column('json_web_token_blacklist', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               schema='auth')
    op.alter_column('json_web_token_blacklist', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               schema='auth')
    op.alter_column('permission_groups', 'permission_id',
               existing_type=sa.UUID(),
               nullable=True,
               schema='auth')
    op.alter_column('permission_groups', 'group_id',
               existing_type=sa.UUID(),
               nullable=True,
               schema='auth')
    op.alter_column('permission_groups', 'date_joined',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               schema='auth')
    op.alter_column('permissions', 'date_joined',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               schema='auth')
    op.alter_column('user_groups', 'date_joined',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               schema='auth')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               schema='auth')
    op.alter_column('users', 'date_joined',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               schema='auth')
    op.alter_column('customers', 'user_id',
               existing_type=sa.UUID(),
               nullable=True,
               schema='customer')
    op.alter_column('customers', 'date_joined',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               schema='customer')
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               schema='product')
    op.alter_column('categories', 'description',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True,
               schema='product')
    op.alter_column('categories', 'product_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='product')
    op.alter_column('categories', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='product')
    op.alter_column('categories', 'date_joined',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               schema='product')
    op.add_column('products', sa.Column('profit_margin', sa.Numeric(precision=5, scale=4), nullable=True), schema='product')
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=60),
               nullable=True,
               schema='product')
    op.alter_column('products', 'categories',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               nullable=True,
               schema='product')
    op.alter_column('products', 'description_short',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               schema='product')
    op.alter_column('products', 'description_long',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True,
               schema='product')
    op.alter_column('products', 'images',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=2048)),
               nullable=True,
               schema='product')
    op.alter_column('products', 'price_neto',
               existing_type=sa.NUMERIC(precision=7, scale=2),
               nullable=True,
               schema='product')
    op.alter_column('products', 'price_sale',
               existing_type=sa.NUMERIC(precision=7, scale=2),
               nullable=True,
               schema='product')
    op.alter_column('products', 'iva',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=True,
               schema='product')
    op.alter_column('products', 'stock_total',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='product')
    op.alter_column('products', 'stock_hand',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='product')
    op.alter_column('products', 'stock_sale',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='product')
    op.alter_column('products', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='product')
    op.alter_column('products', 'date_joined',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               schema='product')
    op.create_index(op.f('ix_product_products_status'), 'products', ['status'], unique=False, schema='product')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_products_status'), table_name='products', schema='product')
    op.alter_column('products', 'date_joined',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               schema='product')
    op.alter_column('products', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               schema='product')
    op.alter_column('products', 'stock_sale',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='product')
    op.alter_column('products', 'stock_hand',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='product')
    op.alter_column('products', 'stock_total',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='product')
    op.alter_column('products', 'iva',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=False,
               schema='product')
    op.alter_column('products', 'price_sale',
               existing_type=sa.NUMERIC(precision=7, scale=2),
               nullable=False,
               schema='product')
    op.alter_column('products', 'price_neto',
               existing_type=sa.NUMERIC(precision=7, scale=2),
               nullable=False,
               schema='product')
    op.alter_column('products', 'images',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=2048)),
               nullable=False,
               schema='product')
    op.alter_column('products', 'description_long',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False,
               schema='product')
    op.alter_column('products', 'description_short',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               schema='product')
    op.alter_column('products', 'categories',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               nullable=False,
               schema='product')
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=60),
               nullable=False,
               schema='product')
    op.drop_column('products', 'profit_margin', schema='product')
    op.alter_column('categories', 'date_joined',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               schema='product')
    op.alter_column('categories', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               schema='product')
    op.alter_column('categories', 'product_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='product')
    op.alter_column('categories', 'description',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False,
               schema='product')
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               schema='product')
    op.alter_column('customers', 'date_joined',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               schema='customer')
    op.alter_column('customers', 'user_id',
               existing_type=sa.UUID(),
               nullable=False,
               schema='customer')
    op.alter_column('users', 'date_joined',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               schema='auth')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               schema='auth')
    op.alter_column('user_groups', 'date_joined',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               schema='auth')
    op.alter_column('permissions', 'date_joined',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               schema='auth')
    op.alter_column('permission_groups', 'date_joined',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               schema='auth')
    op.alter_column('permission_groups', 'group_id',
               existing_type=sa.UUID(),
               nullable=False,
               schema='auth')
    op.alter_column('permission_groups', 'permission_id',
               existing_type=sa.UUID(),
               nullable=False,
               schema='auth')
    op.alter_column('json_web_token_blacklist', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               schema='auth')
    op.alter_column('json_web_token_blacklist', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               schema='auth')
    op.alter_column('json_web_token_blacklist', 'user_id',
               existing_type=sa.UUID(),
               nullable=False,
               schema='auth')
    op.alter_column('json_web_token_blacklist', 'token',
               existing_type=sa.VARCHAR(length=512),
               nullable=False,
               schema='auth')
    op.alter_column('groups', 'date_joined',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               schema='auth')
    op.alter_column('admins', 'date_joined',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               schema='admin')
    op.alter_column('admins', 'user_id',
               existing_type=sa.UUID(),
               nullable=False,
               schema='admin')
    # ### end Alembic commands ###
