"""modelos para la funcionalidad crear cliente

Revision ID: b69911df21ea
Revises: 
Create Date: 2026-03-29 13:36:19.359976

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b69911df21ea'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth.groups',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth.groups_name'), 'auth.groups', ['name'], unique=True)
    op.create_table('auth.permissions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth.permissions_name'), 'auth.permissions', ['name'], unique=True)
    op.create_table('customer.customers',
    sa.Column('first_names', sa.String(length=40), nullable=True),
    sa.Column('last_names', sa.String(length=40), nullable=True),
    sa.Column('document_type', sa.Enum(name='document_type_enum'), nullable=True),
    sa.Column('document_number', sa.String(length=13), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_number'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('auth.permission_groups',
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth.groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['auth.permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth.users',
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('permission_groups_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['permission_groups_id'], ['auth.groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('auth.user_groups',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth.groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth.user_groups')
    op.drop_table('auth.users')
    op.drop_table('auth.permission_groups')
    op.drop_table('customer.customers')
    op.drop_index(op.f('ix_auth.permissions_name'), table_name='auth.permissions')
    op.drop_table('auth.permissions')
    op.drop_index(op.f('ix_auth.groups_name'), table_name='auth.groups')
    op.drop_table('auth.groups')
    # ### end Alembic commands ###
