"""se indexa el campo name del modelo Country

Revision ID: 9cb13a6a00d6
Revises: 849cd13bafe3
Create Date: 2026-10-05 09:10:25.653358

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9cb13a6a00d6"
down_revision: str | Sequence[str] | None = "849cd13bafe3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_country_name"), "country", schema="countries", type_="unique")
    op.create_index(
        op.f("ix_countries_country_name"), "country", ["name"], unique=True, schema="countries"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_countries_country_name"), table_name="country", schema="countries")
    op.create_unique_constraint(
        op.f("uq_country_name"),
        "country",
        ["name"],
        schema="countries",
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
