"""nuevo modelo Product

Revision ID: bbe77706bd62
Revises: c04f2e622b87
Create Date: 2026-05-24 10:54:48.493645

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bbe77706bd62'
down_revision: str | Sequence[str] | None = 'c04f2e622b87'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('categories', sa.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('description_short', sa.String(length=100), nullable=False),
    sa.Column('description_long', sa.String(length=1000), nullable=False),
    sa.Column('images', sa.ARRAY(sa.String(length=2048)), nullable=False),
    sa.Column('price_neto', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('price_sale', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('stock_total', sa.Integer(), nullable=False),
    sa.Column('stock_hand', sa.Integer(), nullable=False),
    sa.Column('stock_sale', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='product'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products', schema='product')
    # ### end Alembic commands ###
