"""se indexa el campo  del modelo

Revision ID: 849cd13bafe3
Revises: e36327183d95
Create Date: 2026-10-02 12:55:56.199269

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "849cd13bafe3"
down_revision: str | Sequence[str] | None = "e36327183d95"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_inventory_products_wholesaler_id"),
        "products",
        ["wholesaler_id"],
        unique=False,
        schema="inventory",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_inventory_products_wholesaler_id"), table_name="products", schema="inventory"
    )
    # ### end Alembic commands ###
