"""Ajuste de implementación de modelos

Revision ID: 24288c210103
Revises: a5f20dc1b98a
Create Date: 2026-04-11 12:20:45.599193

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '24288c210103'
down_revision: str | Sequence[str] | None = 'a5f20dc1b98a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
