"""ajustes en el modelo User

Revision ID: c8c6f928dee6
Revises: 0b3eb6f73b20
Create Date: 2026-05-18 14:44:01.482022

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c8c6f928dee6'
down_revision: str | Sequence[str] | None = '0b3eb6f73b20'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=30), server_default='customer', nullable=False), schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role', schema='auth')
    # ### end Alembic commands ###
