"""nuevo campo en el modelo Product

Revision ID: a27914e9caeb
Revises: cbd59498ef6b
Create Date: 2026-05-30 09:32:06.020172

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a27914e9caeb'
down_revision: str | Sequence[str] | None = 'cbd59498ef6b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('profit_margin', sa.Numeric(precision=5, scale=4), nullable=False), schema='product')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'profit_margin', schema='product')
    # ### end Alembic commands ###
