"""ajustes en los modelos

Revision ID: 172fe293ab25
Revises: c9bba5404f8a
Create Date: 2026-09-29 17:35:34.358232

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "172fe293ab25"
down_revision: str | Sequence[str] | None = "c9bba5404f8a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_products_exclusive_client_id_wholesale"),
        "products",
        schema="product",
        type_="foreignkey",
    )
    op.drop_table("wholesale", schema="users")
    op.create_table(
        "customer_wholesale",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name_or_company_name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=60), nullable=False),
        sa.Column("ruc", sa.String(length=13), nullable=True),
        sa.Column("phone", sa.String(length=25), nullable=False),
        sa.Column("location", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("extra_contacts", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("date_joined", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_wholesale")),
        sa.UniqueConstraint("email", name=op.f("uq_customer_wholesale_email")),
        sa.UniqueConstraint(
            "name_or_company_name",
            name=op.f("uq_customer_wholesale_name_or_company_name"),
        ),
        sa.UniqueConstraint("phone", name=op.f("uq_customer_wholesale_phone")),
        sa.UniqueConstraint("ruc", name=op.f("uq_customer_wholesale_ruc")),
        schema="users",
    )
    op.create_foreign_key(
        op.f("fk_products_exclusive_client_id_customer_wholesale"),
        "products",
        "customer_wholesale",
        ["exclusive_client_id"],
        ["id"],
        source_schema="product",
        referent_schema="users",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_products_exclusive_client_id_customer_wholesale"),
        "products",
        schema="product",
        type_="foreignkey",
    )
    op.drop_table("customer_wholesale", schema="users")
    op.create_table(
        "wholesale",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "name_or_company_name", sa.VARCHAR(length=40), autoincrement=False, nullable=False
        ),
        sa.Column("email", sa.VARCHAR(length=60), autoincrement=False, nullable=False),
        sa.Column("ruc", sa.VARCHAR(length=13), autoincrement=False, nullable=True),
        sa.Column("phone", sa.VARCHAR(length=25), autoincrement=False, nullable=False),
        sa.Column(
            "location",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "extra_contacts",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "date_joined", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wholesale")),
        sa.UniqueConstraint("email", name=op.f("uq_wholesale_email")),
        sa.UniqueConstraint(
            "name_or_company_name", name=op.f("uq_wholesale_name_or_company_name")
        ),
        sa.UniqueConstraint("phone", name=op.f("uq_wholesale_phone")),
        sa.UniqueConstraint("ruc", name=op.f("uq_wholesale_ruc")),
        schema="users",
    )
    op.create_foreign_key(
        op.f("fk_products_exclusive_client_id_wholesale"),
        "products",
        "wholesale",
        ["exclusive_client_id"],
        ["id"],
        source_schema="product",
        referent_schema="users",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
