"""ajustes en el modelo JWTBlaclist

Revision ID: 0682cbc0a5c7
Revises: fafae9db8afc
Create Date: 2026-07-01 14:27:04.920056

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0682cbc0a5c7'
down_revision: str | Sequence[str] | None = 'fafae9db8afc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('json_web_token_blacklist', sa.Column('jti', sa.String(length=200), nullable=True), schema='auth')
    op.add_column('json_web_token_blacklist', sa.Column('token_type', sa.String(length=20), nullable=True), schema='auth')
    op.add_column('json_web_token_blacklist', sa.Column('date_joined', sa.DateTime(timezone=True), nullable=True), schema='auth')
    op.drop_index(op.f('ix_auth_json_web_token_blacklist_token'), table_name='json_web_token_blacklist', schema='auth')
    op.create_index(op.f('ix_auth_json_web_token_blacklist_jti'), 'json_web_token_blacklist', ['jti'], unique=True, schema='auth')
    op.create_index(op.f('ix_auth_json_web_token_blacklist_token_type'), 'json_web_token_blacklist', ['token_type'], unique=True, schema='auth')
    op.create_unique_constraint(None, 'json_web_token_blacklist', ['token'], schema='auth')
    op.drop_column('json_web_token_blacklist', 'created_at', schema='auth')
    op.drop_column('json_web_token_blacklist', 'expires_at', schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('json_web_token_blacklist', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True), schema='auth')
    op.add_column('json_web_token_blacklist', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True), schema='auth')
    op.drop_constraint(None, 'json_web_token_blacklist', schema='auth', type_='unique')
    op.drop_index(op.f('ix_auth_json_web_token_blacklist_token_type'), table_name='json_web_token_blacklist', schema='auth')
    op.drop_index(op.f('ix_auth_json_web_token_blacklist_jti'), table_name='json_web_token_blacklist', schema='auth')
    op.create_index(op.f('ix_auth_json_web_token_blacklist_token'), 'json_web_token_blacklist', ['token'], unique=True, schema='auth')
    op.drop_column('json_web_token_blacklist', 'date_joined', schema='auth')
    op.drop_column('json_web_token_blacklist', 'token_type', schema='auth')
    op.drop_column('json_web_token_blacklist', 'jti', schema='auth')
    # ### end Alembic commands ###
