"""eliminación de modelos innecesarios del módulo countries

Revision ID: 6f156b46a2f9
Revises: 172fe293ab25
Create Date: 2026-09-30 13:18:04.546252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f156b46a2f9'
down_revision: Union[str, Sequence[str], None] = '172fe293ab25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('product_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name')),
    schema='inventory'
    )
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exclusive_client_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('categories', sa.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('description_short', sa.String(length=100), nullable=False),
    sa.Column('description_long', sa.String(length=1000), nullable=False),
    sa.Column('images', sa.ARRAY(sa.String(length=2048)), nullable=False),
    sa.Column('price_neto', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('price_sale', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('profit_margin', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('iva', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('stock_total', sa.Integer(), nullable=False),
    sa.Column('stock_hand', sa.Integer(), nullable=False),
    sa.Column('stock_sale', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exclusive_client_id'], ['users.customer_wholesale.id'], name=op.f('fk_products_exclusive_client_id_customer_wholesale'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('name', name=op.f('uq_products_name')),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_products_status'), 'products', ['status'], unique=False, schema='inventory')
    op.drop_table('organization_ecuador', schema='countries')
    op.drop_table('city_ecuador', schema='countries')
    op.drop_table('categories', schema='product')
    op.drop_table('province_ecuador', schema='countries')
    op.drop_table('canton_ecuador', schema='countries')
    op.drop_index(op.f('ix_product_products_status'), table_name='products', schema='product')
    op.drop_table('products', schema='product')
    op.add_column('country', sa.Column('code', sa.String(length=5), nullable=False), schema='countries')
    op.create_unique_constraint(op.f('uq_country_code'), 'country', ['code'], schema='countries')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_country_code'), 'country', schema='countries', type_='unique')
    op.drop_column('country', 'code', schema='countries')
    op.create_table('products',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exclusive_client_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('categories', postgresql.ARRAY(sa.VARCHAR(length=50)), autoincrement=False, nullable=False),
    sa.Column('description_short', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description_long', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('images', postgresql.ARRAY(sa.VARCHAR(length=2048)), autoincrement=False, nullable=False),
    sa.Column('price_neto', sa.NUMERIC(precision=7, scale=2), autoincrement=False, nullable=False),
    sa.Column('price_sale', sa.NUMERIC(precision=7, scale=2), autoincrement=False, nullable=False),
    sa.Column('profit_margin', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False),
    sa.Column('iva', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False),
    sa.Column('stock_total', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stock_hand', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stock_sale', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('date_joined', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['exclusive_client_id'], ['users.customer_wholesale.id'], name=op.f('fk_products_exclusive_client_id_customer_wholesale'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('name', name=op.f('uq_products_name'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='product'
    )
    op.create_index(op.f('ix_product_products_status'), 'products', ['status'], unique=False, schema='product')
    op.create_table('canton_ecuador',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('date_joined', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_canton_ecuador')),
    sa.UniqueConstraint('name', name=op.f('uq_canton_ecuador_name'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='countries'
    )
    op.create_table('province_ecuador',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('date_joined', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_province_ecuador')),
    sa.UniqueConstraint('name', name=op.f('uq_province_ecuador_name'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='countries'
    )
    op.create_table('categories',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('product_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('date_joined', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='product'
    )
    op.create_table('city_ecuador',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('date_joined', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_city_ecuador')),
    sa.UniqueConstraint('name', name=op.f('uq_city_ecuador_name'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='countries'
    )
    op.create_table('organization_ecuador',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('country_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('province_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('canton_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('city_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date_joined', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['canton_id'], ['countries.canton_ecuador.id'], name=op.f('fk_organization_ecuador_canton_id_canton_ecuador'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['city_id'], ['countries.city_ecuador.id'], name=op.f('fk_organization_ecuador_city_id_city_ecuador'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country.id'], name=op.f('fk_organization_ecuador_country_id_country'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['province_id'], ['countries.province_ecuador.id'], name=op.f('fk_organization_ecuador_province_id_province_ecuador'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_ecuador')),
    schema='countries'
    )
    op.drop_index(op.f('ix_inventory_products_status'), table_name='products', schema='inventory')
    op.drop_table('products', schema='inventory')
    op.drop_table('categories', schema='inventory')
    # ### end Alembic commands ###
