"""nueva columna session_version en el modelo user

Revision ID: fafae9db8afc
Revises: dbc78487bfd6
Create Date: 2026-06-30 16:23:46.572249

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fafae9db8afc'
down_revision: str | Sequence[str] | None = 'dbc78487bfd6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               schema='auth')
    op.alter_column('permissions', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               schema='auth')
    op.add_column('users', sa.Column('session_version', sa.Integer(), nullable=True), schema='auth')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=60),
               nullable=True,
               schema='auth')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               schema='auth')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=60),
               nullable=False,
               schema='auth')
    op.drop_column('users', 'session_version', schema='auth')
    op.alter_column('permissions', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               schema='auth')
    op.alter_column('groups', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               schema='auth')
    # ### end Alembic commands ###
